language: csharp
solution: IntegracionContinua.Poligran.sln

install:
  - nuget restore IntegracionContinua.Poligran.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release IntegracionContinua.Poligran.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./IntegracionContinua.Poligran.Tests/bin/Release/IntegracionContinua.Poligran.Tests.dll