apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: dotnet pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Build dotnet app
        uses: docker://golang:1.20.3-alpine3.17
        run: |
          dotnet build
